name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # Choisis les versions de Node.js que tu souhaites tester

    steps:
      - uses: actions/checkout@v2 # Récupère le code source du dépôt
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install # Installe les dépendances
      - run: npm test # Exécute les tests
